# permissions for end users to view gitea.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitea-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gitea-operator
    app.kubernetes.io/part-of: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitea-viewer-role
rules:
- apiGroups:
  - api.gitea.k8s
  resources:
  - gitea
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.gitea.k8s
  resources:
  - gitea/status
  verbs:
  - get
