---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.gitea.k8s
  resources:
  - gitea
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.gitea.k8s
  resources:
  - gitea/finalizers
  verbs:
  - update
- apiGroups:
  - api.gitea.k8s
  resources:
  - gitea/status
  verbs:
  - get
  - patch
  - update
