apiVersion: api.gitea.k8s/v1alpha1
kind: Gitea
metadata:
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea-sample
    app.kubernetes.io/part-of: gitea-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitea-operator
  name: gitea-sample
spec:
  # TODO(user): Add fields here
